development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: volunteer_index_development
  pool: 5
  username: volunteer_index
  password: fabc125
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: volunteer_index_production
  pool: 5
  username: volunteer_index
  password: fabc125
  socket: /var/run/mysqld/mysqld.sock
